#!/usr/bin/env python

import os
import sys
import glob

mega_url = "https://mega.co.nz/"
file_prefix = "list_"
def main(argv):
    """docstring for main"""

    if len(argv) < 3:
        print("%s <list> <slice_number>" % argv[0])
        return -1

    dl_file = argv[1]
    slice_n = int(argv[2])

    if not os.path.exists(dl_file):
        print("File Not Found. %s" % dl_file)

    valid_list = []
    invalid_list = []
    totally = None
    with open(dl_file, 'rb') as f:
        totally = f.readlines()
        for l in totally:
            if l.startswith('https://mega.co.nz/'):
                valid_list.append(l)
            else:
                invalid_list.append(l)

    valid_n = len(valid_list)
    npf = valid_n/slice_n

    for i in xrange(slice_n):
        with open(file_prefix + str(i), 'wb') as f:
            if i == 0:
                # first
                f.writelines(invalid_list + valid_list[i * npf:((i + 1)*npf)-1])
            elif i == (slice_n - 1):
                #last
                f.writelines(valid_list[i * npf:])
            else:
                f.writelines(valid_list[i * npf:((i + 1)*npf)-1])

if __name__ == '__main__':
    main(sys.argv)

