#!/usr/bin/env python

import os
import sys
import glob

mega_url = "https://mega.co.nz/"
file_prefix = "list_"
def main(argv):
    """docstring for main"""

    if len(argv) < 3:
        print("%s <list> <slice_number>" % argv[0])
        return -1

    dl_file = argv[1]
    slice_n = int(argv[2])

    if not os.path.exists(dl_file):
        print("File Not Found. %s" % dl_file)

    valid_list = []
    invalid_list = []
    totally = None
    with open(dl_file, 'rb') as f:
        totally = f.readlines()
        for l in totally:
            if l.startswith('https://mega.co.nz/'):
                valid_list.append(l)
            else:
                invalid_list.append(l)

    valid_n = len(valid_list)
    npf = valid_n/slice_n

    fs = [ open(file_prefix + str(i), 'a') for i in xrange(slice_n) ]

    fs[0].writelines(invalid_list)
    for n in xrange(len(valid_list)):
        fs[n%(slice_n)].writelines(valid_list[n])

    [ close(f) for f in fs ]

if __name__ == '__main__':
    main(sys.argv)

